-- AlterTable
ALTER TABLE `pengunjung` ADD COLUMN `jumlahAnak` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `jumlahBalita` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `jumlahDewasa` INTEGER NOT NULL DEFAULT 0,
    MODIFY `jumlah` INTEGER NOT NULL DEFAULT 0;
